// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: app/slammapping/v1/slammapping.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartMappingSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StartMappingSessionRequest) Reset() {
	*x = StartMappingSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_slammapping_v1_slammapping_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartMappingSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMappingSessionRequest) ProtoMessage() {}

func (x *StartMappingSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_slammapping_v1_slammapping_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMappingSessionRequest.ProtoReflect.Descriptor instead.
func (*StartMappingSessionRequest) Descriptor() ([]byte, []int) {
	return file_app_slammapping_v1_slammapping_proto_rawDescGZIP(), []int{0}
}

func (x *StartMappingSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StartMappingSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartMappingSessionResponse) Reset() {
	*x = StartMappingSessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_slammapping_v1_slammapping_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartMappingSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMappingSessionResponse) ProtoMessage() {}

func (x *StartMappingSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_slammapping_v1_slammapping_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMappingSessionResponse.ProtoReflect.Descriptor instead.
func (*StartMappingSessionResponse) Descriptor() ([]byte, []int) {
	return file_app_slammapping_v1_slammapping_proto_rawDescGZIP(), []int{1}
}

type GetMappingSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMappingSessionRequest) Reset() {
	*x = GetMappingSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_slammapping_v1_slammapping_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMappingSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMappingSessionRequest) ProtoMessage() {}

func (x *GetMappingSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_slammapping_v1_slammapping_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMappingSessionRequest.ProtoReflect.Descriptor instead.
func (*GetMappingSessionRequest) Descriptor() ([]byte, []int) {
	return file_app_slammapping_v1_slammapping_proto_rawDescGZIP(), []int{2}
}

func (x *GetMappingSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMappingSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PointCloud []byte `protobuf:"bytes,1,opt,name=point_cloud,json=pointCloud,proto3" json:"point_cloud,omitempty"`
}

func (x *GetMappingSessionResponse) Reset() {
	*x = GetMappingSessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_slammapping_v1_slammapping_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMappingSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMappingSessionResponse) ProtoMessage() {}

func (x *GetMappingSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_slammapping_v1_slammapping_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMappingSessionResponse.ProtoReflect.Descriptor instead.
func (*GetMappingSessionResponse) Descriptor() ([]byte, []int) {
	return file_app_slammapping_v1_slammapping_proto_rawDescGZIP(), []int{3}
}

func (x *GetMappingSessionResponse) GetPointCloud() []byte {
	if x != nil {
		return x.PointCloud
	}
	return nil
}

var File_app_slammapping_v1_slammapping_proto protoreflect.FileDescriptor

var file_app_slammapping_v1_slammapping_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x70, 0x70, 0x2f, 0x73, 0x6c, 0x61, 0x6d, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6c, 0x61, 0x6d, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x76, 0x69, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x70,
	0x2e, 0x73, 0x6c, 0x61, 0x6d, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x22,
	0x2c, 0x0a, 0x1a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1d, 0x0a,
	0x1b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2a, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3c, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x32, 0x93, 0x02, 0x0a, 0x12, 0x53, 0x4c, 0x41, 0x4d, 0x4d,
	0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x80, 0x01,
	0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x2e, 0x76, 0x69, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x70,
	0x2e, 0x73, 0x6c, 0x61, 0x6d, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x76, 0x69, 0x61,
	0x6d, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x73, 0x6c, 0x61, 0x6d, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x7a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x2e, 0x76, 0x69, 0x61, 0x6d, 0x2e, 0x61, 0x70, 0x70,
	0x2e, 0x73, 0x6c, 0x61, 0x6d, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x76, 0x69, 0x61, 0x6d, 0x2e,
	0x61, 0x70, 0x70, 0x2e, 0x73, 0x6c, 0x61, 0x6d, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x24, 0x5a, 0x22,
	0x67, 0x6f, 0x2e, 0x76, 0x69, 0x61, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x70, 0x70, 0x2f, 0x73, 0x6c, 0x61, 0x6d, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_slammapping_v1_slammapping_proto_rawDescOnce sync.Once
	file_app_slammapping_v1_slammapping_proto_rawDescData = file_app_slammapping_v1_slammapping_proto_rawDesc
)

func file_app_slammapping_v1_slammapping_proto_rawDescGZIP() []byte {
	file_app_slammapping_v1_slammapping_proto_rawDescOnce.Do(func() {
		file_app_slammapping_v1_slammapping_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_slammapping_v1_slammapping_proto_rawDescData)
	})
	return file_app_slammapping_v1_slammapping_proto_rawDescData
}

var file_app_slammapping_v1_slammapping_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_app_slammapping_v1_slammapping_proto_goTypes = []interface{}{
	(*StartMappingSessionRequest)(nil),  // 0: viam.app.slammapping.v1.StartMappingSessionRequest
	(*StartMappingSessionResponse)(nil), // 1: viam.app.slammapping.v1.StartMappingSessionResponse
	(*GetMappingSessionRequest)(nil),    // 2: viam.app.slammapping.v1.GetMappingSessionRequest
	(*GetMappingSessionResponse)(nil),   // 3: viam.app.slammapping.v1.GetMappingSessionResponse
}
var file_app_slammapping_v1_slammapping_proto_depIdxs = []int32{
	0, // 0: viam.app.slammapping.v1.SLAMMappingService.StartMappingSession:input_type -> viam.app.slammapping.v1.StartMappingSessionRequest
	2, // 1: viam.app.slammapping.v1.SLAMMappingService.GetMappingSession:input_type -> viam.app.slammapping.v1.GetMappingSessionRequest
	1, // 2: viam.app.slammapping.v1.SLAMMappingService.StartMappingSession:output_type -> viam.app.slammapping.v1.StartMappingSessionResponse
	3, // 3: viam.app.slammapping.v1.SLAMMappingService.GetMappingSession:output_type -> viam.app.slammapping.v1.GetMappingSessionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_slammapping_v1_slammapping_proto_init() }
func file_app_slammapping_v1_slammapping_proto_init() {
	if File_app_slammapping_v1_slammapping_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_slammapping_v1_slammapping_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartMappingSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_slammapping_v1_slammapping_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartMappingSessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_slammapping_v1_slammapping_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMappingSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_slammapping_v1_slammapping_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMappingSessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_slammapping_v1_slammapping_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_slammapping_v1_slammapping_proto_goTypes,
		DependencyIndexes: file_app_slammapping_v1_slammapping_proto_depIdxs,
		MessageInfos:      file_app_slammapping_v1_slammapping_proto_msgTypes,
	}.Build()
	File_app_slammapping_v1_slammapping_proto = out.File
	file_app_slammapping_v1_slammapping_proto_rawDesc = nil
	file_app_slammapping_v1_slammapping_proto_goTypes = nil
	file_app_slammapping_v1_slammapping_proto_depIdxs = nil
}
